name: Deploy Water Tenant

on:
  push:
    branches:
      # - dev
      # - test
      # - main
      # disabled the pipeline for the water tenant.
      # while assets (prompt templates) are still being deployed manually via portal.
      - other 
    paths:
      - 'src/tenant/water/**'
      - 'src/shared/**'
      - 'src/index.js'
      - 'scripts/build-tenant.mjs'
      - 'package.json'
      - '.github/workflows/deploy-tenant-reusable.yml'
      - '.github/workflows/deploy-water.yml'

jobs:
  deploy-water:
    uses: ./.github/workflows/deploy-tenant-reusable.yml
    secrets: inherit
    with:
      tenant: water
      deployment_environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
